name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - name: Lint
        run: npx eslint . --ext .ts,.vue

      - name: Format Check
        run: npx prettier --check .

      - name: Run Tests
        run: npx vitest run
